# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/linlo001/TDP005/hangry_frogs

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/linlo001/TDP005/hangry_frogs

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/linlo001/TDP005/hangry_frogs/CMakeFiles /home/linlo001/TDP005/hangry_frogs//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/linlo001/TDP005/hangry_frogs/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named game

# Build rule for target.
game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 game
.PHONY : game

# fast build rule for target.
game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/build
.PHONY : game/fast

actionbar.o: actionbar.cc.o
.PHONY : actionbar.o

# target to build an object file
actionbar.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/actionbar.cc.o
.PHONY : actionbar.cc.o

actionbar.i: actionbar.cc.i
.PHONY : actionbar.i

# target to preprocess a source file
actionbar.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/actionbar.cc.i
.PHONY : actionbar.cc.i

actionbar.s: actionbar.cc.s
.PHONY : actionbar.s

# target to generate assembly for a file
actionbar.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/actionbar.cc.s
.PHONY : actionbar.cc.s

button.o: button.cc.o
.PHONY : button.o

# target to build an object file
button.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/button.cc.o
.PHONY : button.cc.o

button.i: button.cc.i
.PHONY : button.i

# target to preprocess a source file
button.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/button.cc.i
.PHONY : button.cc.i

button.s: button.cc.s
.PHONY : button.s

# target to generate assembly for a file
button.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/button.cc.s
.PHONY : button.cc.s

enemy.o: enemy.cc.o
.PHONY : enemy.o

# target to build an object file
enemy.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/enemy.cc.o
.PHONY : enemy.cc.o

enemy.i: enemy.cc.i
.PHONY : enemy.i

# target to preprocess a source file
enemy.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/enemy.cc.i
.PHONY : enemy.cc.i

enemy.s: enemy.cc.s
.PHONY : enemy.s

# target to generate assembly for a file
enemy.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/enemy.cc.s
.PHONY : enemy.cc.s

entity.o: entity.cc.o
.PHONY : entity.o

# target to build an object file
entity.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/entity.cc.o
.PHONY : entity.cc.o

entity.i: entity.cc.i
.PHONY : entity.i

# target to preprocess a source file
entity.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/entity.cc.i
.PHONY : entity.cc.i

entity.s: entity.cc.s
.PHONY : entity.s

# target to generate assembly for a file
entity.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/entity.cc.s
.PHONY : entity.cc.s

game_engine.o: game_engine.cc.o
.PHONY : game_engine.o

# target to build an object file
game_engine.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game_engine.cc.o
.PHONY : game_engine.cc.o

game_engine.i: game_engine.cc.i
.PHONY : game_engine.i

# target to preprocess a source file
game_engine.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game_engine.cc.i
.PHONY : game_engine.cc.i

game_engine.s: game_engine.cc.s
.PHONY : game_engine.s

# target to generate assembly for a file
game_engine.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game_engine.cc.s
.PHONY : game_engine.cc.s

main.o: main.cc.o
.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i
.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s
.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/main.cc.s
.PHONY : main.cc.s

pepe.o: pepe.cc.o
.PHONY : pepe.o

# target to build an object file
pepe.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/pepe.cc.o
.PHONY : pepe.cc.o

pepe.i: pepe.cc.i
.PHONY : pepe.i

# target to preprocess a source file
pepe.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/pepe.cc.i
.PHONY : pepe.cc.i

pepe.s: pepe.cc.s
.PHONY : pepe.s

# target to generate assembly for a file
pepe.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/pepe.cc.s
.PHONY : pepe.cc.s

turret.o: turret.cc.o
.PHONY : turret.o

# target to build an object file
turret.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/turret.cc.o
.PHONY : turret.cc.o

turret.i: turret.cc.i
.PHONY : turret.i

# target to preprocess a source file
turret.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/turret.cc.i
.PHONY : turret.cc.i

turret.s: turret.cc.s
.PHONY : turret.s

# target to generate assembly for a file
turret.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/turret.cc.s
.PHONY : turret.cc.s

world.o: world.cc.o
.PHONY : world.o

# target to build an object file
world.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/world.cc.o
.PHONY : world.cc.o

world.i: world.cc.i
.PHONY : world.i

# target to preprocess a source file
world.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/world.cc.i
.PHONY : world.cc.i

world.s: world.cc.s
.PHONY : world.s

# target to generate assembly for a file
world.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/world.cc.s
.PHONY : world.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... game"
	@echo "... actionbar.o"
	@echo "... actionbar.i"
	@echo "... actionbar.s"
	@echo "... button.o"
	@echo "... button.i"
	@echo "... button.s"
	@echo "... enemy.o"
	@echo "... enemy.i"
	@echo "... enemy.s"
	@echo "... entity.o"
	@echo "... entity.i"
	@echo "... entity.s"
	@echo "... game_engine.o"
	@echo "... game_engine.i"
	@echo "... game_engine.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... pepe.o"
	@echo "... pepe.i"
	@echo "... pepe.s"
	@echo "... turret.o"
	@echo "... turret.i"
	@echo "... turret.s"
	@echo "... world.o"
	@echo "... world.i"
	@echo "... world.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

